- type: entity
  id: ThrusterSyndicateMachineCircuitboard
  parent: [BaseMachineCircuitboard, BaseC3ContrabandUnredeemable]
  name: двигатель Синдиката
  components:
  - type: Sprite
    state: security
  - type: MachineBoard
    prototype: ThrusterSyndicate
    requirements:
      Capacitor: 2
    stackRequirements:
      Steel: 5
      Cable: 2

- type: entity
  id: SyndicateTechFabCircuitboard
  parent: [SecurityTechFabCircuitboard, BaseC3ContrabandUnredeemable]
  name: ТехФаб синдиката (машинная плата)
  description: Плата для создания техфаба синдиката.
  components:
    - type: Sprite
      state: security
    - type: MachineBoard
      prototype: SyndicateTechFab