- type: entity
  id: ThrusterSyndicateMachineCircuitboard
  parent: [BaseMachineCircuitboard, BaseC3ContrabandUnredeemable]
  name: двигатель Синдиката
  components:
  - type: Sprite
    state: security
  - type: MachineBoard
    prototype: ThrusterSyndicate
    requirements:
      Capacitor: 2
    stackRequirements:
      Steel: 5
      Cable: 2