- type: job
  id: Commander
  name: Командир
  description: Глава штурмовой группы "Жнецы"
  playTimeTracker: JobCommander
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1 # 48 hours
  startingGear: CommanderGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconCommander"
  supervisors: job-supervisors-nobody
  weight: 40
  displayWeight: 40
  setPreference: true
  access:
  - GeneraSyndicatelAccess
  accessGroups:
  - GeneraSyndicatelAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - SyndicateNF
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplanter ]

- type: startingGear
  id: CommanderGear
  equipment:
    ears: ClothingHeadsetAltSyndicate
    id: SyndiPDA
    belt: ClothingBeltAssault
    pocket1: WeaponPistolPollock
    mask: ClothingMaskGasSwat
  storage:
    back:
    - BoxSurvivalNFOxygenExtended
    - MagazinePistol
    - MagazinePistol