- type: startingGear
  id: SyndicateReinforcementSpySmugger
  parent: SyndicateOperativeClothing
  equipment:
    id: AgentIDCard
    mask: ClothingMaskGasVoiceChameleon
    pocket1: WeaponPistolViper
  storage:
    back:
    - ToolboxKadet